project:
  type: website

website:
  title: "Reportes"
  favicon: favicon.ico   # Puedes agregar un ícono personalizado
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Inicio
      - href: SegundoDavid_U1_T1.ipynb
        text: Unidad 1
      - href: SegundoDavid_U2_T1.ipynb
        text: Unidad 2
      - href: SegundoDavid_U3_T1.ipynb
        text: Unidad 3
      - href: SegundoDavid_U4_T1.ipynb
        text: Unidad 4
      - href: SegundoDavid_U5_T1.ipynb
        text: Unidad 5
      - href: cambios.ipynb
        text: Cambios
  page-footer:
    left: "© 2025 David Segundo García"
    right: 
      - icon: github
        href: https://github.com/DavidSG24/An-lisis-de-algoritmos

format:
  html:
    theme:
      light: cosmo     # Más profesional y claro
      dark: darkly     # Tema oscuro moderno
    toc: true
    toc-location: right
    toc-title: "Contenido"
    css: styles.css
    code-copy: true
    code-overflow: wrap
